exclude = [
    ".git",
    "__pycache",
    "migrations",
    "src",
    "docs",
    "rh_django_shared",
    "example/conf/settings.py",
]

[lint]
dummy-variable-rgx = "_|dummy"
# See https://github.com/astral-sh/ruff?tab=readme-ov-file#rules for all supported rules
select = [
    "A",
    "B",
    "BLE",
    "C",
    "C4",
    "C90",
    "COM",
    "DJ",
    "DTZ",
    "E",
    "ERA",
    "F",
    "G",
    "I",
    "ICN",
    "INP",
    "N",
    "PIE",
    "PGH",
    "PL",
    "PTH",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "T20",
    "UP",
    "W",
    "YTT",
]
ignore = [
#    "N802",     # Function name `{name}` should be lowercase
    "N803",     # Argument name `{name}` should be lowercase
#    "N806",     # Variable `{name}` in function should be lowercase
#    "N815",     # Variable `{name}` in class scope should not be mixedCase
#    "N818",     # Exception name `{name}` should be named with an Error suffix
#    "A003",     # Class attribute `{name}` is shadowing a python builtin
#    "S101",     # Use of `assert` detected
#    "UP007",    # Use `X | Y` for type annotations
    "S105",     # Possible hardcoded password: "{}"
#    "PLR0913",  # Too many arguments to function call ({c_args}/{max_args})
    "RUF012",   # Mutable class attributes should be annotated with `typing.ClassVar`
]

[lint.mccabe]
max-complexity = 16

[lint.pycodestyle]
max-line-length = 88

[lint.pylint]
max-branches = 16
max-args = 10
max-public-methods = 50

[format]
skip-magic-trailing-comma = false

[lint.pyflakes]
extend-generics = ["django_kafka.registry.Registry"]
