---
services:
  app:
    build: .
    user: app
    entrypoint: /app/manage.py
    command: runserver 0:8000
    volumes:
      - .:/app:cached
    environment:
      SHELL: /bin/bash
      IPYTHONDIR: /app/.ipython
      HISTFILE: /app/.bash_history
      PYTHONPATH: /app  # make app available without installation
    restart: "no"
