# Generated by Django 5.2.3 on 2025-06-25 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_kafka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Waiting'), (2, 'Resolving'), (3, 'Resolved')], default=1, verbose_name='status')),
                ('key', models.BinaryField(verbose_name='key')),
                ('value', models.BinaryField(verbose_name='value')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('topic', models.TextField(verbose_name='topic')),
                ('partition', models.TextField(verbose_name='partition')),
                ('offset', models.TextField(verbose_name='offset')),
                ('headers', models.JSONField(null=True, verbose_name='headers')),
                ('relation_id_field', models.CharField(max_length=256, verbose_name='relation id field')),
                ('relation_id_value', models.CharField(max_length=256, verbose_name='relation id value')),
                ('serialized_relation', models.JSONField(verbose_name='relation kwargs')),
                ('relation_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'waiting message',
                'verbose_name_plural': 'waiting messages',
                'ordering': ('offset',),
            },
        ),
    ]
