# Generated by Django 5.2.1 on 2025-05-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kafka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationResolverCacheModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_identifier', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='relation identifier')),
            ],
            options={
                'verbose_name': 'relation resolver tracker',
                'verbose_name_plural': 'relation resolver tracker',
            },
        ),
    ]
