# Generated by Django 5.2.9 on 2026-06-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kafka', '0002_waitingmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingmessage',
            name='_headers',
            field=models.JSONField(blank=True, null=True, verbose_name='headers'),
        ),
    ]
