# Generated by Django 6.0.4 on 2026-06-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kafka', '0003_alter_waitingmessage__headers'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='waitingmessage',
            index=models.Index(fields=['topic', 'key'], name='django_kafka_topic_key_idx'),
        ),
    ]
