# Generated by Django 6.0.6 on 2026-07-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kafka', '0004_waitingmessage_django_kafka_topic_key_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='waitingmessage',
            index=models.Index(fields=['relation_model_key', 'relation_id_field', 'relation_id_value'], name='django_kafka_relation_idx'),
        ),
    ]
