# Generated by Django 5.2.9 on 2026-07-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kafka', '0005_waitingmessage_django_kafka_relation_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyOffsetTracker',
        ),
    ]
