# Generated by Django 6.0.6 on 2026-08-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kafka', '0006_delete_keyoffsettracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingmessage',
            name='offset',
            field=models.BigIntegerField(verbose_name='offset'),
        ),
        migrations.AlterField(
            model_name='waitingmessage',
            name='partition',
            field=models.IntegerField(verbose_name='partition'),
        ),
    ]
